/// <autosync enabled="true" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-1.10.2.js" />
/// <reference path="jquery-3.1.1.js" />
/// <reference path="jquery-3.1.1.slim.js" />
/// <reference path="js/entercode.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="moment.min.js" />
/// <reference path="moment-with-locales.min.js" />
/// <reference path="respond.js" />
/// <reference path="respond.matchmedia.addListener.js" />
/// <reference path="sweetalert.min.js" />
/// <reference path="underscore-min.js" />
//# sourceMappingURL=_references.js.map